version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Maps port 80 in the container to port 3000 on the host

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env  # Make sure this is properly indented
    environment:
      - MongoDB_URI=${MongoDB_URI}  # Ensure this matches the variable in your .env
    ports:
      - "5000:5000" # Maps port 5000 in the container to port 5000 on the host
